### ISSUE TITLE
entrust .der files are PEM files

### ISSUE THREAD

**Issue by baentsch** [IETF-Hackathon/pqc-certificates#11]
@johngray-dev, fyi. Verify scripts failing in consequence (mistakenly trying to generate (again) PEM files)

**Comment by johngray-dev** [comment]
Thanks Michael, I think I have fixed those issues now, and will be posting a new artifact.zip today or tomorrow....

**Comment by johngray-dev** [comment]
I just posted a new version that should resolve those issues.   The .der files are actually binary ASN.1 files.
