### ISSUE TITLE
Failure running make cross_verify in oqs-gnutls

### ISSUE THREAD

**Issue by baentsch** [IETF-Hackathon/pqc-certificates#64]
When running this command, this happened:

```
s$ make cross_verify

[ gnutls ] Checking Requirements (Verify):
[ gnutls ] Done (Ok)
/bin/sh: 3: Syntax error: ";" unexpected
Makefile:110: recipe for target 'cross_verify' failed
make: *** [cross_verify] Error 2
```

Looking at [the code](https://github.com/IETF-Hackathon/pqc-certificates/blob/6789aff996b90f69b3b22545e39f0a211a56f367/providers/oqs-gnutls/Makefile#L115) the logic seems to be incorrect in that it simply runs each project's own "verify" but not on another project's artifacts (?)

Lastly, this code does not seem to generate the report CSV files. Are you still active on this @ueno ?

**Comment by ueno** [comment]
@baentsch yes, let me take a look.

**Comment by baentsch** [comment]
> @baentsch yes, let me take a look.

Thanks very much! See https://github.com/IETF-Hackathon/pqc-certificates/pull/65 for a general OQS (also data) update (should you want to use this for your testing).

**Comment by ueno** [comment]
#66 should fix the shell syntax error; the same issue also happens with other providers (carl-redhound, corey-digicert, entrust, and kris) in the current master branch.

As for the actual cross verification logic, I'll check separately.
